version: "3.9"

services:
  sync:
    build: .
    container_name: sync_${INSTANCE:-default}
    volumes:
      # Settings folder with project yaml and service account credentials
      - ./settings:/app/settings:ro
      # All folders mounted in the Docker container from host machine for syncing
      - ${SOURCE_FOLDER_01:-.}:/mnt/source_01:${SOURCE_FOLDER_01_MODE:-ro}

    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS:-/app/settings/service-account-key.json}
      - CLOUDSDK_CORE_PROJECT=${CLOUDSDK_CORE_PROJECT}
      - CLOUDSDK_COMPUTE_REGION=${CLOUDSDK_COMPUTE_REGION}

    restart: unless-stopped
